export const browserMode=import.meta.env.MODE==='pages';
export type RecordEntry={id:string;date:string;caption:string;rotation:number;created:string;image?:string};
function db():Promise<IDBDatabase>{return new Promise((resolve,reject)=>{const r=indexedDB.open('food-sticker-diary',1);r.onupgradeneeded=()=>r.result.createObjectStore('stickers',{keyPath:'id'});r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(new Error('无法打开浏览器存储，请检查隐私模式或存储权限'));});}
async function all():Promise<RecordEntry[]>{const d=await db();try{return await new Promise((resolve,reject)=>{const t=d.transaction('stickers','readonly');const r=t.objectStore('stickers').getAll();r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});}finally{d.close();}}
async function write(rows:RecordEntry[],remove?:string){const d=await db();try{await new Promise<void>((resolve,reject)=>{const t=d.transaction('stickers','readwrite');const s=t.objectStore('stickers');rows.forEach(row=>s.put(row));if(remove)s.delete(remove);t.oncomplete=()=>resolve();t.onerror=()=>reject(new Error('保存失败，浏览器空间可能不足，请先导出备份'));t.onabort=()=>reject(new Error('保存未完成，请重试'));});}finally{d.close();}}
function validate(v:RecordEntry){if(!v||typeof v.id!=='string'||!/^[a-f0-9-]{36}$/.test(v.id)||typeof v.date!=='string'||!/^\d{4}-\d{2}-\d{2}$/.test(v.date)||isNaN(Date.parse(v.date))||new Date(v.date).toISOString().slice(0,10)!==v.date||typeof v.caption!=='string'||v.caption.length>100||typeof v.rotation!=='number'||!Number.isFinite(v.rotation)||Math.abs(v.rotation)>20||typeof v.image!=='string'||!/^data:image\/png;base64,[A-Za-z0-9+/=]+$/.test(v.image)||v.image.length>12*1024*1024)throw Error('备份中的记录格式无效');}
export async function request(url:string,method='GET',body?:unknown):Promise<unknown>{if(!browserMode){const r=await fetch(url,{method,...(body?{headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:{})});const data=await r.json() as {error?:string};if(!r.ok)throw new Error(data.error||'操作失败，请重试');return data;}
const entries=await all();if(method==='GET'){const month=new URL(url,location.origin).searchParams.get('month');return entries.filter(e=>e.date.startsWith(month||'')).sort((a,b)=>a.created.localeCompare(b.created));}
const id=url.split('/').pop();if(method==='DELETE'){await write([],id);return {ok:true};}
if(method==='POST'){const row={...(body as RecordEntry),created:new Date().toISOString()};validate(row);if(!entries.some(e=>e.id===row.id))await write([row]);return {id:row.id};}
if(method==='PATCH'){const current=entries.find(e=>e.id===id);if(!current)throw Error('记录不存在，请刷新');const row={...current,...(body as RecordEntry),id:current.id,image:current.image,created:current.created};validate(row);await write([row]);return {ok:true};}throw Error('不支持的操作');}
export function stickerImage(entry:RecordEntry){return browserMode?entry.image||'':'/api/stickers/'+entry.id+'/image';}
export async function exportBackup(){return JSON.stringify({format:'food-sticker-diary',version:1,exportedAt:new Date().toISOString(),records:await all()},null,2);}
export async function importBackup(file:File){if(file.size>100*1024*1024)throw Error('请使用 100 MB 以内的备份');const value=JSON.parse(await file.text());if(value.format!=='food-sticker-diary'||value.version!==1||!Array.isArray(value.records)||value.records.length>10000)throw Error('不是有效的食日记备份');const records=value.records as RecordEntry[];records.forEach(validate);for(const r of records){if(typeof r.created!=='string'||isNaN(Date.parse(r.created)))throw Error('备份日期无效');const image=await createImageBitmap(await(await fetch(r.image!)).blob());if(image.width>4096||image.height>4096){image.close();throw Error('备份图片尺寸过大');}image.close();}const existing=new Set((await all()).map(r=>r.id));const additions=records.filter((r,i)=>!existing.has(r.id)&&records.findIndex(x=>x.id===r.id)===i);await write(additions);return additions.length;}
