'use client';
import {useState,useRef,useEffect,type CSSProperties} from 'react';
import {Camera,ImagePlus,ChevronLeft,ChevronRight,Plus,Scissors,MoveUpRight,Check,Sticker,Trash2,RotateCcw,Loader2,Upload,X,Sparkles,CalendarDays,HardDrive} from 'lucide-react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {AlertDialog,AlertDialogContent,AlertDialogHeader,AlertDialogTitle,AlertDialogDescription,AlertDialogFooter,AlertDialogCancel,AlertDialogAction} from '@/components/ui/alert-dialog';
import {Slider} from '@/components/ui/slider';
import {Toaster,toast} from 'sonner';
import {request,stickerImage,browserMode} from '../local/storage';
import {Backup} from '../local/backup';
import {Inspiration,PaperPalette,Memories} from '../local/journal-extras';
import {preparePhoto,cropSticker,dataUrl} from '../local/photo';
type FoodSticker={id:string;date:string;caption:string;rotation:number;created:string;image?:string};
type Draft={id:string;date:string;caption:string;rotation:number;blob:Blob;url:string;original:string};
const today=()=>format(new Date());
function format(d:Date){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;}
function label(d:string){return new Date(d+'T12:00:00').toLocaleDateString('zh-CN',{month:'long',day:'numeric',weekday:'long'});}
export default function Home(){
 const [selected,setSelected]=useState(today);const [month,setMonth]=useState(()=>today().slice(0,7));const [items,setItems]=useState<FoodSticker[]>([]);const [loading,setLoading]=useState(true);const [loadError,setLoadError]=useState('');const [draft,setDraft]=useState<Draft|null>(null);const [editing,setEditing]=useState<FoodSticker|null>(null);const [deleting,setDeleting]=useState<FoodSticker|null>(null);const [saving,setSaving]=useState(false);const [busy,setBusy]=useState(false);const [progress,setProgress]=useState('');const [original,setOriginal]=useState('');const [processError,setProcessError]=useState('');const [compare,setCompare]=useState(false);const [camera,setCamera]=useState(false);const [cameraError,setCameraError]=useState('');const [cameraReady,setCameraReady]=useState(false);const [dragging,setDragging]=useState('');const [dropDate,setDropDate]=useState('');const [fresh,setFresh]=useState('');const [fileOver,setFileOver]=useState(false);
 const picker=useRef<HTMLInputElement>(null);const video=useRef<HTMLVideoElement>(null);const stream=useRef<MediaStream|null>(null);const worker=useRef<Worker|null>(null);const lastFile=useRef<File|null>(null);const job=useRef(0);const req=useRef(0);const uploadDate=useRef(selected);const dragSource=useRef('');const urls=useRef<string[]>([]);
 function objectUrl(blob:Blob){const u=URL.createObjectURL(blob);urls.current.push(u);return u;}
 function cleanImages(){for(const u of urls.current)URL.revokeObjectURL(u);urls.current=[];setOriginal('');}
 async function load(m:string){const token=++req.current;setLoading(true);setLoadError('');try{const result=await request('/api/stickers?month='+m);if(token===req.current)setItems(result as unknown as FoodSticker[]);}catch(e){if(token===req.current){setLoadError((e as Error).message);setItems([]);}}finally{if(token===req.current)setLoading(false);}}
 useEffect(()=>{void load(month);},[month]);
 useEffect(()=>()=>{worker.current?.terminate();stream.current?.getTracks().forEach(t=>t.stop());urls.current.forEach(u=>URL.revokeObjectURL(u));},[]);
 useEffect(()=>{if(!camera)return;let active=true;setCameraError('');setCameraReady(false);navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'},width:{ideal:1600}},audio:false}).then(s=>{if(!active){s.getTracks().forEach(t=>t.stop());return;}stream.current=s;if(video.current){video.current.srcObject=s;void video.current.play().then(()=>setCameraReady(true));}}).catch(()=>setCameraError('无法打开摄像头。请允许相机权限，或选择已有照片。'));return()=>{active=false;stream.current?.getTracks().forEach(t=>t.stop());stream.current=null;};},[camera]);
 function chooseDay(d:string){setSelected(d);if(d.slice(0,7)!==month)setMonth(d.slice(0,7));}
 function navigate(n:number){const d=new Date(month+'-01T12:00:00');d.setMonth(d.getMonth()+n);const m=format(d).slice(0,7);setMonth(m);setSelected(m+'-01');}
 function pick(){uploadDate.current=selected;picker.current?.click();}
 async function processPhoto(file:File){if(busy||saving)return;if(!['image/jpeg','image/png','image/webp','image/avif'].includes(file.type)){toast.error('请选择 JPG、PNG、WebP 或 AVIF 图片');return;}if(file.size>25*1024*1024){toast.error('请选择 25 MB 以内的照片');return;}cleanImages();lastFile.current=file;const token=++job.current;setBusy(true);setProcessError('');setProgress('正在整理照片…');setOriginal(objectUrl(file));try{
 const photo=await preparePhoto(file);if(token!==job.current)return;setProgress('正在本地剪出食物…');const w=new Worker(new URL('../local/cutout.worker.ts',import.meta.url),{type:'module'});worker.current=w;
 const result=await new Promise<Blob>((resolve,reject)=>{w.onmessage=e=>{if(token!==job.current)return;const m=e.data;if(m.type==='done')resolve(m.blob);if(m.type==='error')reject(new Error(m.message));if(m.type==='progress'&&m.key?.startsWith('fetch:'))setProgress(m.current===m.total?'正在本地剪出食物…':'正在加载本地抠图模型…');};w.onerror=()=>reject(new Error('抠图引擎未能启动'));w.postMessage({blob:photo,publicPath:new URL(import.meta.env.BASE_URL+"models/",location.origin).href});});w.terminate();worker.current=null;if(token!==job.current)return;const cutout=await cropSticker(result);setDraft({id:crypto.randomUUID(),date:uploadDate.current,caption:'',rotation:Math.round(Math.random()*12-6),blob:cutout,url:objectUrl(cutout),original:objectUrl(photo)});setCompare(false);setBusy(false);
 }catch(e){if(token===job.current){console.error(e);setProcessError('这张照片暂时没能抠好。请重试，或换一张主体清晰的照片。');setBusy(false);worker.current?.terminate();worker.current=null;}}}
 function cancelProcess(){job.current++;worker.current?.terminate();worker.current=null;setBusy(false);setProcessError('');lastFile.current=null;cleanImages();}
 async function capture(){if(!video.current||!cameraReady)return;const v=video.current;const c=document.createElement('canvas');c.width=v.videoWidth;c.height=v.videoHeight;c.getContext('2d')!.drawImage(v,0,0);const blob=await new Promise<Blob|null>(r=>c.toBlob(r,'image/jpeg',.94));if(!blob){toast.error('拍摄失败，请重试');return;}uploadDate.current=selected;setCamera(false);void processPhoto(new File([blob],'camera.jpg',{type:'image/jpeg'}));}
 async function save(){if(!draft||saving)return;setSaving(true);try{await request('/api/stickers','POST',{id:draft.id,date:draft.date,caption:draft.caption,rotation:draft.rotation,image:await dataUrl(draft.blob)});const d=draft.date;setFresh(draft.id);setDraft(null);cleanImages();chooseDay(d);if(month===d.slice(0,7))await load(month);toast.success('贴好啦！又收藏了一口美味。');}catch(e){toast.error((e as Error).message);}finally{setSaving(false);}}
 async function update(entry:FoodSticker){if(saving)return;setSaving(true);try{await request('/api/stickers/'+entry.id,'PATCH',entry);setEditing(null);setFresh(entry.id);chooseDay(entry.date);if(entry.date.slice(0,7)===month)await load(month);toast.success('贴纸已更新');}catch(e){toast.error((e as Error).message);}finally{setSaving(false);}}
 async function remove(){if(!deleting||saving)return;setSaving(true);try{await request('/api/stickers/'+deleting.id,'DELETE');setDeleting(null);setEditing(null);await load(month);toast.success('已移除这张贴纸');}catch(e){toast.error((e as Error).message);}finally{setSaving(false);}}
 async function drop(e:React.DragEvent,d:string){e.preventDefault();e.stopPropagation();setDropDate('');setDragging('');if(busy||saving)return;if(e.dataTransfer.files.length){uploadDate.current=d;chooseDay(d);void processPhoto(e.dataTransfer.files[0]);return;}const id=e.dataTransfer.getData('text/sticker-id');const item=items.find(x=>x.id===id);if(item&&item.date!==d)await update({...item,date:d});}
 const start=new Date(month+'-01T12:00:00');const offset=(start.getDay()+6)%7;const count=new Date(start.getFullYear(),start.getMonth()+1,0).getDate();const cellCount=Math.ceil((offset+count)/7)*7;const days=Array.from({length:cellCount},(_,i)=>{const d=new Date(start);d.setDate(i-offset+1);return format(d);});const selectedItems=items.filter(i=>i.date===selected);const recordedDays=new Set(items.map(i=>i.date)).size;const [year,monthNo]=month.split('-');
 return <><Toaster position="bottom-center" richColors/><input ref={picker} className="sr-only" type="file" accept="image/jpeg,image/png,image/webp,image/avif" aria-label="上传食物照片" onChange={e=>{const f=e.target.files?.[0];e.target.value='';if(f)void processPhoto(f);}}/>
 <header className="site-header"><a className="brand" href={import.meta.env.BASE_URL}><span className="brand-icon"><Sticker size={24}/></span><span>食日记<span className="brand-sub">TINY BITES, BIG MEMORIES</span></span></a><span className="local-badge"><HardDrive size={14}/>{browserMode?"保存在这个浏览器":"保存在这台电脑"}</span></header>
 <main className="scrapbook"><div className="page-heading"><div><div className="eyebrow">MY EDIBLE SCRAPBOOK</div><h1>把好吃的，<span>贴进日历。</span><Sparkles className="heading-spark" size={25}/></h1><p>拍一张，剪一剪。日子也有了好吃的形状。</p></div><button className="primary camera-top" disabled={busy||saving} onClick={()=>setCamera(true)}><Camera size={19}/>拍下这一餐</button></div>
 <PaperPalette/><div className="desk"><section className="calendar-paper" aria-label="饮食贴纸月历"><div className="binding" aria-hidden="true">{Array.from({length:12},(_,i)=><span key={i}/>)}</div><div className="calendar-top"><div className="month-title"><span className="month-number">{monthNo}</span><div><strong>{year} / {Number(monthNo)}月</strong><span>{['JANUARY','FEBRUARY','MARCH','APRIL','MAY','JUNE','JULY','AUGUST','SEPTEMBER','OCTOBER','NOVEMBER','DECEMBER'][Number(monthNo)-1]}</span></div></div><div className="month-nav"><button aria-label="上个月" onClick={()=>navigate(-1)} disabled={saving}><ChevronLeft size={18}/></button><button className="today-button" onClick={()=>chooseDay(today())} disabled={saving}>今天</button><button aria-label="下个月" onClick={()=>navigate(1)} disabled={saving}><ChevronRight size={18}/></button></div></div>
 <div className="calendar-stats"><span><b>{items.length}</b> 张美味贴纸 <i>·</i> <b>{recordedDays}</b> 天的好好吃饭</span><span className="drag-tip"><MoveUpRight size={13}/> 拖动贴纸，换个日子</span></div>
 {loadError&&<div className="load-error" role="alert">{loadError}<button onClick={()=>load(month)}>重试</button></div>}
 <div className="weekdays">{['MON 一','TUE 二','WED 三','THU 四','FRI 五','SAT 六','SUN 日'].map(s=><span key={s}>{s}</span>)}</div><div className={'calendar-grid '+(loading?'is-loading':'')} aria-busy={loading}>{days.map(d=>{const list=items.filter(i=>i.date===d);return <div key={d} role="group" aria-label={d} className={'day-cell '+(d===selected?'selected ':'')+(d===today()?'is-today ':'')+(d.slice(0,7)!==month?'outside ':'')+(dropDate===d?'drop-target':'')} onDragOver={e=>{if(e.dataTransfer.types.includes('Files')||e.dataTransfer.types.includes('text/sticker-id')){e.preventDefault();setDropDate(d);}}} onDragLeave={e=>{if(!e.currentTarget.contains(e.relatedTarget as Node))setDropDate('');}} onDrop={e=>void drop(e,d)}><button className="day-select" onClick={()=>chooseDay(d)} aria-label={'选择'+d} aria-pressed={d===selected}><span>{Number(d.slice(-2))}</span>{d===today()&&<em>今天</em>}</button><div className="sticker-pile">{list.slice(0,4).map((s,i)=><button key={s.id} draggable={!saving} aria-label={'查看贴纸：'+(s.caption||'美味一餐')} className={'food-sticker sticker-'+i+' '+(fresh===s.id?'just-pasted ':'')+(dragging===s.id?'being-dragged':'')} style={{'--angle':s.rotation+'deg'} as CSSProperties} onDragStart={e=>{e.dataTransfer.setData('text/sticker-id',s.id);e.dataTransfer.effectAllowed='move';setDragging(s.id);dragSource.current=s.id;}} onDragEnd={()=>{setDragging('');setDropDate('');setTimeout(()=>{dragSource.current='';},100);}} onClick={()=>{if(!dragSource.current)setEditing({...s});}}><img src={stickerImage(s)} alt={s.caption||'食物贴纸'} draggable={false}/></button>)}{list.length>4&&<button className="more-stickers" onClick={()=>chooseDay(d)}>+{list.length-4}</button>}{!list.length&&d===selected&&<button className="empty-day-add" aria-label="为选中日期添加照片" disabled={busy||saving} onClick={pick}><Plus size={19}/><span>贴一张</span></button>}</div></div>;})}</div><div className="paper-footer"><span>GOOD FOOD. GOOD MOOD.</span><span>一点一滴，都是生活。<span className="footer-star">✳</span></span></div></section>
 <aside className="studio"><section className="upload-card"><div className="tape" aria-hidden="true"/><div className="studio-title"><Scissors size={19}/><h2>贴纸小工坊</h2><span>01—02—03</span></div><div className={'upload-zone '+(fileOver?'file-over':'')} onDragOver={e=>{e.preventDefault();setFileOver(true);}} onDragLeave={()=>setFileOver(false)} onDrop={e=>{e.preventDefault();setFileOver(false);if(!busy&&!saving&&e.dataTransfer.files[0]){uploadDate.current=selected;void processPhoto(e.dataTransfer.files[0]);}}}>
 <span className="upload-icon"><ImagePlus size={33}/></span><h3>今天吃了什么？</h3><p>放进一张照片<br/>自动变成一枚美味贴纸</p><button className="upload-button" onClick={pick} disabled={busy||saving}><Plus size={16}/>选择照片</button><button className="camera-link" onClick={()=>setCamera(true)} disabled={busy||saving}><Camera size={15}/>或直接拍一张</button><span className="file-hint">也可以把照片拖到这里 · 最大 25 MB</span></div><div className="steps"><span><b>1</b>拍照</span><i/><span><b>2</b>自动抠图</span><i/><span><b>3</b>贴进日历</span></div><p className="photo-tip">单份食物、简洁背景，剪出来更好看。</p></section>
 <section className="day-notes"><div className="day-notes-head"><div><span className="eyebrow">A LITTLE TASTE OF TODAY</span><h2>{label(selected).replace('星期','周')}</h2></div><span className="count-label">{selectedItems.length} 张</span></div>{selectedItems.length?<div className="day-thumbnails">{selectedItems.map(s=><button key={s.id} onClick={()=>setEditing({...s})}><img src={stickerImage(s)} alt={s.caption||'食物贴纸'} style={{transform:`rotate(${s.rotation}deg)`}}/><span>{s.caption||'美味一餐'}</span></button>)}</div>:<div className="no-stickers"><CalendarDays size={23}/><p>这一天，留给美味的空白。</p><button onClick={pick} disabled={busy||saving}>收藏第一口</button></div>}</section><Inspiration/><p className="desk-note">不算热量，只收藏快乐。<span>enjoy every bite ♡</span></p></aside></div><Memories items={items} month={month} onEdit={setEditing} loading={loading} error={loadError}/><Backup onImport={()=>void load(month)}/><footer className="site-footer"><span>食日记 / FOOD JOURNAL</span><span>照片在本地处理，记忆留在你这里。</span></footer></main>
 <Dialog open={busy||!!processError} onOpenChange={v=>{if(!v)cancelProcess();}}><DialogContent className="cutout-modal"><DialogTitle>{processError?'再试一次，剪得更好':'正在制作你的贴纸'}</DialogTitle><DialogDescription>{processError?'原照片仍然保留，可以重新尝试。':'正在本地识别食物并去掉背景，首次处理会稍慢一些。'}</DialogDescription><div className="processing-photo">{original&&<img src={original} alt="待抠图的食物照片"/>}{busy&&<div className="scanline"/>}<span><Scissors size={22}/></span></div>{busy?<div className="process-status" role="status"><Loader2 className="spin" size={18}/>{progress}</div>:<><p className="inline-error" role="alert">{processError}</p><button className="primary" onClick={()=>{if(lastFile.current)void processPhoto(lastFile.current);}}>重新抠图</button></>}<button className="quiet" onClick={cancelProcess}>取消</button></DialogContent></Dialog>
 <Dialog open={!!draft} onOpenChange={v=>{if(!v&&!saving){setDraft(null);cleanImages();}}}><DialogContent className="sticker-modal" showCloseButton={!saving} onEscapeKeyDown={e=>{if(saving)e.preventDefault();}} onPointerDownOutside={e=>{if(saving)e.preventDefault();}}><DialogTitle>一枚新鲜出炉的贴纸</DialogTitle><DialogDescription>给这一口美味，找个日子贴下来。</DialogDescription>{draft&&<><div className={'sticker-preview '+(compare?'show-original':'')}><img src={compare?draft.original:draft.url} alt={compare?'原始照片':'去除背景后的食物贴纸'} style={{transform:compare?'none':`rotate(${draft.rotation}deg)`}}/><button className="compare" onClick={()=>setCompare(!compare)}>{compare?'看贴纸':'看原图'}</button><span className="preview-tag">{compare?'ORIGINAL':'FRESHLY CUT ✦'}</span></div><div className="form-row"><label>贴在哪一天<input type="date" required value={draft.date} disabled={saving} onChange={e=>setDraft({...draft,date:e.target.value})}/></label><label>写个小名字 <span>选填</span><input placeholder="比如：幸福感满分的早餐" maxLength={100} value={draft.caption} disabled={saving} onChange={e=>setDraft({...draft,caption:e.target.value})}/></label></div><div className="rotation-control"><span>歪一点，更可爱</span><Slider aria-label="贴纸旋转角度" min={-15} max={15} step={1} value={[draft.rotation]} disabled={saving} onValueChange={v=>setDraft({...draft,rotation:v[0]})}/><button aria-label="摆正贴纸" onClick={()=>setDraft({...draft,rotation:0})} disabled={saving}><RotateCcw size={16}/></button></div><button className="primary paste-button" disabled={saving||!draft.date} onClick={()=>void save()}>{saving?<Loader2 className="spin" size={18}/>:<Sticker size={18}/>} {saving?'正在保存…':'就贴在这一天'}</button></>}</DialogContent></Dialog>
 <Dialog open={!!editing} onOpenChange={v=>{if(!v&&!saving)setEditing(null);}}><DialogContent className="sticker-modal" showCloseButton={!saving}><DialogTitle>这一口的小记忆</DialogTitle><DialogDescription>可以改个日期、转个角度，或加一句备注。</DialogDescription>{editing&&<><div className="sticker-preview"><img src={stickerImage(editing)} alt={editing.caption||'食物贴纸'} style={{transform:`rotate(${editing.rotation}deg)`}}/></div><div className="form-row"><label>日期<input type="date" value={editing.date} disabled={saving} onChange={e=>setEditing({...editing,date:e.target.value})}/></label><label>小名字<input maxLength={100} value={editing.caption} disabled={saving} onChange={e=>setEditing({...editing,caption:e.target.value})}/></label></div><div className="rotation-control"><span>贴纸角度</span><Slider aria-label="修改贴纸角度" min={-15} max={15} value={[editing.rotation]} disabled={saving} onValueChange={v=>setEditing({...editing,rotation:v[0]})}/></div><div className="edit-actions"><button className="delete-button" disabled={saving} onClick={()=>setDeleting(editing)}><Trash2 size={16}/>移除贴纸</button><button className="primary" disabled={saving||!editing.date} onClick={()=>void update(editing)}><Check size={17}/>保存</button></div></>}</DialogContent></Dialog>
 <Dialog open={camera} onOpenChange={setCamera}><DialogContent className="camera-modal"><DialogTitle>把这一餐拍下来</DialogTitle><DialogDescription>让食物占据画面中心，背景简单一点。</DialogDescription><video ref={video} autoPlay playsInline muted className="camera-video"/>{cameraError&&<p className="inline-error" role="alert">{cameraError}</p>}<div className="camera-actions"><button className="quiet" onClick={()=>{setCamera(false);pick();}}><Upload size={16}/>选择照片</button><button className="primary" disabled={!cameraReady} onClick={()=>void capture()}><Camera size={18}/>拍摄</button></div></DialogContent></Dialog>
 <AlertDialog open={!!deleting} onOpenChange={v=>{if(!v&&!saving)setDeleting(null);}}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>移除这枚贴纸？</AlertDialogTitle><AlertDialogDescription>会从日历和本地记录中删除“{deleting?.caption||'美味一餐'}”，无法撤销。</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel disabled={saving}>再留一会儿</AlertDialogCancel><AlertDialogAction disabled={saving} onClick={e=>{e.preventDefault();void remove();}}>确认移除</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
 </>;
}


