'use client';
import { useEffect, useRef, useState } from 'react';
import { BookOpen, ChevronLeft, ChevronRight, Plus, Sun, Sunset, Moon, Apple, Pencil, Trash2, Check, X, Utensils, LockKeyhole } from 'lucide-react';
import { RadioGroup, RadioGroupItem } from '@/components/ui/radio-group';
import { AlertDialog, AlertDialogContent, AlertDialogHeader, AlertDialogTitle, AlertDialogDescription, AlertDialogFooter, AlertDialogCancel, AlertDialogAction } from '@/components/ui/alert-dialog';
type Entry = { id:string; date:string; meal:string; food:string; amount:string; note:string };
const meals = ['早餐','午餐','晚餐','加餐']; const icons = [Sun,Sunset,Moon,Apple];
function day(d = new Date()) { return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`; }
const fresh = (date:string, meal='早餐'):Entry => ({ id:'',date,meal,food:'',amount:'',note:'' });
async function api(method:string, data:unknown) { const r = await fetch('/api/meals', {method, headers:{'Content-Type':'application/json'}, body:JSON.stringify(data)}); const result = await r.json() as {error?:string}; if (!r.ok) throw new Error(result.error || '操作失败，请重试'); return result; }
export default function Home() {
 const [signedIn,setSignedIn]=useState(true); const [date,setDate]=useState(''); const [entries,setEntries]=useState<Entry[]>([]); const [draft,setDraft]=useState<Entry>(fresh('')); const [loading,setLoading]=useState(true); const [error,setError]=useState(''); const [saveError,setSaveError]=useState(''); const [busy,setBusy]=useState(false); const [notice,setNotice]=useState(''); const [remove,setRemove]=useState<Entry|null>(null); const input=useRef<HTMLInputElement>(null); const request=useRef(0);
 useEffect(()=>{ const d=day(); setDate(d); setDraft(fresh(d)); },[]);
 async function load(d:string) { const ticket=++request.current; setLoading(true); setError(''); try { const r=await fetch('/api/meals?date='+d); const data=await r.json(); if(r.status===401) { if(ticket===request.current) {setSignedIn(false);setEntries([]);} return; } if(!r.ok) throw new Error((data as {error:string}).error); if(ticket===request.current) setEntries(data as Entry[]); } catch(e) { if(ticket===request.current) { setError((e as Error).message); setEntries([]); } } finally { if(ticket===request.current) setLoading(false); } }
 useEffect(()=>{ if(date) void load(date); },[date]);
 useEffect(()=>{ const ctx=(document as unknown as {modelContext?:{registerTool:(tool:unknown,options:unknown)=>void}}).modelContext; if(!ctx) return; const ctrl=new AbortController(); try { ctx.registerTool({name:'read_food_diary',description:'读取指定日期的饮食记录，不修改内容。',inputSchema:{type:'object',properties:{date:{type:'string',pattern:'^\\d{4}-\\d{2}-\\d{2}$'}},required:['date'],additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:async (v:{date:string})=>{ if(!/^\d{4}-\d{2}-\d{2}$/.test(v.date)) throw new Error('日期无效'); const r=await fetch('/api/meals?date='+v.date); const data=await r.json(); if(!r.ok) throw new Error((data as {error:string}).error); return data; }},{signal:ctrl.signal}); } catch {} return ()=>ctrl.abort(); },[]);
 function shift(n:number) { const d=new Date(date+'T12:00:00'); d.setDate(d.getDate()+n); setDate(day(d)); }
 function start(meal:string) { setDraft(fresh(date,meal)); setSaveError(''); setNotice(''); input.current?.focus(); document.getElementById('entry-form')?.scrollIntoView({behavior:'smooth',block:'nearest'}); }
 async function save(e:React.FormEvent) { e.preventDefault(); if(busy) return; setBusy(true); setSaveError(''); setNotice(''); const payload={...draft,id:draft.id||crypto.randomUUID()}; try { await api(draft.id?'PUT':'POST',payload); setDraft(fresh(draft.date,draft.meal)); setNotice('已保存这一餐'); if(date===draft.date) await load(date); else setDate(draft.date); } catch(e) { setSaveError((e as Error).message); } finally {setBusy(false);} }
 async function deleteEntry() { if(!remove) return; setBusy(true); setSaveError(''); try { await api('DELETE',{id:remove.id}); if(draft.id===remove.id) setDraft(fresh(date)); setRemove(null); setNotice('记录已删除'); await load(date); } catch(e) { setSaveError((e as Error).message); setRemove(null); } finally {setBusy(false);} }
 const completed=new Set(entries.map(e=>e.meal)).size;
 return <><header className="topbar"><a className="brand" href="/"><span className="brandmark"><Utensils size={23}/></span>食日记<span className="brand-en">FOOD JOURNAL</span></a><span className="private"><LockKeyhole size={14}/>每日饮食日记</span></header><main>
 <section className="intro"><div><div className="eyebrow">EVERY BITE, A LITTLE MEMORY</div><h1>好好吃饭，慢慢记录。</h1><p>把每天的滋味，留在这里。</p></div><img className="food-photo" src="/food-photo.jpg" alt="色彩丰富的新鲜蔬菜"/></section>
 {!signedIn&&<div className="signin-banner"><div><strong>记录属于你的每一餐</strong><p>登录后保存饮食日记，只有你能查看自己的记录。</p></div><a href="/signin-with-chatgpt?return_to=%2F" target="_top">使用 ChatGPT 登录</a></div>}<div className="workspace"><section className="journal"><div className="journal-head"><div><span className="eyebrow">MY DAILY PLATE</span><h2>每日饮食</h2></div><button className="today" onClick={()=>setDate(day())} disabled={busy}>回到今天</button></div>
 <div className="datebar"><button aria-label="前一天" onClick={()=>shift(-1)} disabled={!date||busy}><ChevronLeft size={20}/></button><label className="date-label"><input aria-label="查看日期" type="date" value={date} onChange={e=>{if(e.target.value)setDate(e.target.value);}} disabled={busy}/><span>{date?new Date(date+'T12:00:00').toLocaleDateString('zh-CN',{weekday:'long'}):''}{date===day()?' · 今天':''}</span></label><button aria-label="后一天" onClick={()=>shift(1)} disabled={!date||busy}><ChevronRight size={20}/></button></div>
 <div className="summary"><span><strong>{loading?'—':entries.length}</strong> 项食物</span><i/><span><strong>{loading?'—':completed}</strong> / 4 餐已记录</span><div className="meal-dots">{meals.map(m=><span key={m} className={entries.some(e=>e.meal===m)?'filled':''}/>)}</div></div>
 {error?<div className="error" role="alert">{error}<button onClick={()=>load(date)}>重新加载</button></div>:loading?<div className="loading" role="status">正在翻开这一天的记录…</div>:<div className="meal-list">{meals.map((meal,i)=>{const Icon=icons[i];const items=entries.filter(e=>e.meal===meal);return <article className="meal" key={meal}><div className={'meal-icon meal-'+i}><Icon size={22}/></div><div className="meal-content"><div className="meal-title"><h3>{meal}<span>{['BREAKFAST','LUNCH','DINNER','SNACK'][i]}</span></h3><button className="add" onClick={()=>start(meal)} aria-label={'添加'+meal} disabled={busy}><Plus size={18}/></button></div>{items.length?items.map(item=><div className="food-entry" key={item.id}><div><strong>{item.food}</strong>{item.amount&&<span className="amount">{item.amount}</span>}{item.note&&<p>{item.note}</p>}</div><div className="entry-actions"><button aria-label={'编辑'+item.food} disabled={busy} onClick={()=>{setDraft(item);setSaveError('');setNotice('');input.current?.focus();}}><Pencil size={15}/></button><button aria-label={'删除'+item.food} disabled={busy} onClick={()=>setRemove(item)}><Trash2 size={15}/></button></div></div>):<p className="empty-copy">还没记下这一餐 <button onClick={()=>start(meal)} disabled={busy}>记一笔</button></p>}</div></article>;})}</div>}
 <div className="journal-foot"><BookOpen size={16}/> 不必每餐都完美，记录就是一个好开始。</div></section>
 <aside><form id="entry-form" onSubmit={save}><div className="form-head"><span className="form-icon"><Plus size={22}/></span><div><h2>{draft.id?'编辑这一餐':'记下这一餐'}</h2><p>刚刚吃了什么？</p></div>{draft.id&&<button type="button" aria-label="取消编辑" onClick={()=>setDraft(fresh(date))}><X size={18}/></button>}</div>
 <label className="field">日期<input type="date" required value={draft.date} disabled={busy} onChange={e=>setDraft({...draft,date:e.target.value})}/></label><div className="field">餐次<RadioGroup className="meal-options" value={draft.meal} onValueChange={meal=>setDraft({...draft,meal})} disabled={busy}>{meals.map(m=><label className={draft.meal===m?'selected':''} key={m}><RadioGroupItem value={m} id={'meal-'+m}/>{m}</label>)}</RadioGroup></div>
 <label className="field">食物名称 <span className="required">*</span><input ref={input} placeholder="例如：番茄鸡蛋面" maxLength={100} required value={draft.food} disabled={busy} onChange={e=>setDraft({...draft,food:e.target.value})}/></label><label className="field">份量 <span className="optional">选填</span><input placeholder="例如：1 碗、2 个、半份" maxLength={80} value={draft.amount} disabled={busy} onChange={e=>setDraft({...draft,amount:e.target.value})}/></label><label className="field">备注 <span className="optional">选填</span><textarea rows={3} placeholder="口味、心情，或想记住的小事…" maxLength={500} value={draft.note} disabled={busy} onChange={e=>setDraft({...draft,note:e.target.value})}/></label>
 {saveError&&<div className="error" role="alert">{saveError}</div>}{notice&&<div className="success" role="status"><Check size={16}/>{notice}</div>}<button className="save" disabled={busy||!date||!signedIn} type="submit">{busy?'正在保存…':draft.id?'保存修改':'保存记录'}{!busy&&<Check size={18}/>}</button><p className="save-note"><LockKeyhole size={12}/>记录为你私人保存</p></form><div className="aside-note"><span>ONE DAY AT A TIME</span><p>认真对待每一餐，<br/>也温柔对待自己。</p></div></aside></div><footer>食日记 <span>·</span> 生活的滋味，值得被记住。</footer></main>
 <AlertDialog open={!!remove} onOpenChange={open=>{if(!open&&!busy)setRemove(null);}}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>删除这条记录？</AlertDialogTitle><AlertDialogDescription>将删除“{remove?.food}”，此操作无法撤销。</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel disabled={busy}>保留记录</AlertDialogCancel><AlertDialogAction disabled={busy} onClick={e=>{e.preventDefault();void deleteEntry();}}>确认删除</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog></>;
}


